import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import AosLayout from "@/components/AosLayout";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AosLayout>
          <div className="flex flex-col min-h-[100dvh] overflow-x-hidden">
            <div className="flex flex-col flex-1  ">{children}</div>
          </div>
        </AosLayout>
      </body>
    </html>
  );
}
